apiVersion: apps/v1
kind: Deployment
metadata:
  name: shz-deployment
  namespace: default
  labels:
    app: shz-v1
    owner: admin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shz-v1
  template:
    metadata:
      labels:
        app: shz-v1
    spec:
      containers:
      - name: web-app
        image: ghcr.io/thamizh-kumaran-01/shz-app@sha256:2a2e66956858ee00a5f16733dae1cce1ac972d352577b8bb855a1aaad8dc1980
        command: ["./app"]  # Adjust this if your app binary has a different name
        ports:
        - containerPort: 80
