apiVersion: apps/v1
kind: Deployment
metadata:
  name: shz-deployment
  namespace: default
  labels:
    app: shz-v1
    owner: admin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shz-v1
  template:
    metadata:
      labels:
        app: shz-v1
    spec:
      containers:
      - name: web-app
        image: ghcr.io/thamizh-kumaran-01/shz-app:a00c799879300d5f7b499f1fd004acd475952f5cc368490f232aef52f86846c568e4cf6cbf95fde4
        ports:
        - containerPort: 80
