name: SHZ CI Pipeline

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/shz-app

jobs:
  build-and-secure:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Cosign
      uses: sigstore/cosign-installer@v3.5.0

    - name: Log into GitHub Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker Image
      run: docker build -t ${{ env.IMAGE_NAME }}:${{ github.sha }} ./my-app

    - name: Trivy Vulnerability Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ env.IMAGE_NAME }}:${{ github.sha }}'
        format: 'table'
        exit-code: '0'
        ignore-unfixed: true

    - name: Generate SBOM
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ env.IMAGE_NAME }}:${{ github.sha }}'
        format: 'spdx-json'
        output: 'sbom.spdx.json'

    - name: Push to Registry
      run: docker push ${{ env.IMAGE_NAME }}:${{ github.sha }}

    - name: Sign Image with Cosign
      run: cosign sign --yes ${{ env.IMAGE_NAME }}:${{ github.sha }}
